python ./codes/metrics/get_user_metrics.py \
--dir_name_in get_sentence_loss_file_samples_sub_id_long.csv_model_ClinicalBERT_1a_nsamples_1_date_29_12_2021_09_48_34  \
--dir_name_out  get_sentence_loss_file_i2b2_samples_sub_id_long.csv_model_ClinicalBERT_1a_nsamples_1_date_29_12_2021_10_52_27 \
--dir_name_ref_in get_sentence_loss_file_samples_sub_id_long.csv_model_pubmed_nsamples_1_date_29_12_2021_09_45_51 \
--dir_name_ref_out get_sentence_loss_file_i2b2_samples_sub_id_long.csv_model_pubmed_nsamples_1_date_29_12_2021_11_21_28 \
--dir_name_train_in   get_sentence_loss_file_samples_sub_id_long_2.csv_model_ClinicalBERT_1a_nsamples_1_date_29_12_2021_13_44_05  \
--dir_name_train_out    get_sentence_loss_file_samples_sub_id_long_2.csv_model_pubmed_nsamples_1_date_29_12_2021_15_40_36  \
--dir_name_population_in  get_sentence_loss_file_i2b2_samples_sub_id_long_2.csv_model_ClinicalBERT_1a_nsamples_1_date_29_12_2021_14_31_21  \
--dir_name_population_out   get_sentence_loss_file_i2b2_samples_sub_id_long_2.csv_model_pubmed_nsamples_1_date_29_12_2021_16_51_55 \
--file_name_in /home/fmireshg/berglab.projects/sent_extraction/sample_extract/CSV_Files/samples_sub_id_long.csv \
--file_name_ref /home/fmireshg/berglab.projects/sent_extraction/sample_extract/CSV_Files/i2b2_samples_sub_id_long.csv \
--file_name_train /home/fmireshg/berglab.projects/sent_extraction/sample_extract/CSV_Files/samples_sub_id_long_2.csv \
--file_name_population /home/fmireshg/berglab.projects/sent_extraction/sample_extract/CSV_Files/i2b2_samples_sub_id_long_2.csv \

